# Generated by Django 4.0.4 on 2022-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='master_photo',
            field=models.ImageField(blank=True, default='media/master_photo_default.jpg', null=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
