# Generated by Django 4.0.4 on 2022-05-23 12:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+375XX XXX-XX-XX', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
