# Generated by Django 4.0.4 on 2022-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_masters_master_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='master_photo',
            field=models.ImageField(blank=True, default='media/master_photo_default.jpg', null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
