# Generated by Django 4.0.4 on 2022-05-19 09:59

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('client_surname', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Фамилия')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='+375XX XXX-XX-XX', max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('master_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('master_surname', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Фамилия')),
                ('master_photo', models.ImageField(blank=True, default='api/static/master_photos/master_photo_default.jpg', null=True, upload_to='api/static/master_photos/', verbose_name='Фото')),
                ('master_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='+375XX-XXX-XX-XX', max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Услуга')),
                ('service_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена')),
                ('service_duration', models.TimeField(choices=[(datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30')], verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Дата посещения')),
                ('order_time', models.TimeField(choices=[(datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30')], verbose_name='Время посещения')),
                ('client_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clients')),
                ('master_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.masters')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.services')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='masters',
            name='master_skills',
            field=models.ManyToManyField(to='api.services', verbose_name='Навыки'),
        ),
    ]
